name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  draft-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: false
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generateReleaseNotes: true
    outputs:
      tag: ${{ github.ref_name }}

  build:
    name: Build ${{ matrix.artifact_name }}
    runs-on: ${{ matrix.os }}
    needs: draft-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: medal-aarch64-android

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: medal-x86_64-linux-musl

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: medal-x86_64-macos

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: medal-aarch64-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./medal -> target"

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.target }}
          args: "-p medal --release"
          toolchain: "nightly"
          strip: true

      - name: Rename artifact
        shell: bash
        run: |
          ARTIFACT_DIR="target/${{ matrix.target }}/release"
          mv "${ARTIFACT_DIR}/medal" "${ARTIFACT_DIR}/${{ matrix.artifact_name }}"

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ needs.draft-release.outputs.tag }}
          overwrite: true
